apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pas de base/ pour ce composant : un Corefile est propre à une distribution
# Kubernetes ET à un cluster. Le mutualiser serait une fausse bonne idée.
resources:
- coredns.yaml
