apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- namespace.yaml
- postgres.yaml
- externalsecret-openwebui.yaml
- externalsecret-grafana.yaml
- keycloak.yaml
- realm-platform.yaml
- httproute.yaml
